name: 'Setup Mikero Command Line Tools'
description: 'Set up a Mikero Command Line Tools in the PATH'
author: 'SCHTAMP'
inputs:
  direct-build:
    description: 'If true, build-path will be packed directly. If false, all dirs in build-path will be packed'
    required: false
  path:
    description: 'Path to directory to build'
    required: false
  build-path:
    description: 'Path where build PBOs will be stored'
    required: true
branding:
  icon: trash-2
  color: green
runs:
  using: 'node12'
  main: 'dist/index.js'